let arr = ['Iya magana maa da raanarsa', 'Say kogo ya tsagé kadangaré yaké samun chiga', 'Hantsi leqa gidan kowa',
'idan raana ta fito tafin hannu baya karé ta', 'Dan guntun gatarinka yafi sari ka bani', 'Gaskya dokin qarfé', 'May néma na taré da samu', ];

function magana () {
    var numarr = Math.floor(Math.random()*(6));
    document.getElementById('generateur').innerHTML = arr[numarr];

}

let poete = document.getElementById('poete');


let poesie = [
    `Mes dames et monsieur…respectez vos entourages….
    Souriez pour eux et….ayez le sens du partage….
    Sœurs et frères, qui compatissent quand vos cœurs se….départagent….
    Ceux-là qui vous débloquent et….. Vous facilitez l’affichage….
    Ces sœurs, ces frères et…ces amis qui vous soutiennent même quand vos sentiments voyagent…
    Ils ont en eux tout l’amour qu’il faut pour…vous faire tourner une page….
    Ils ont…….
    Ils ont ce pouvoir que je surnomme…l’anti dérapage….
    Ceux-là qui…même quand tout semble perdu et que vous êtes à terres…vous redonne le courage…. 
    Ceux-là, ceux-là….
    C’est cela la devise de mon entourage…mon chez moi….
    Je vais vous parler de…chez moi….
     Un chez moi où…les amis vous protègent du soleil comme…les nuages du quinze de ce moi….
    Quand je parle de chez moi, je…ne veux pas être celui-là qui reste sur son quant à soi….
    Je parle de chez moi avec fierté et au final c’est…un slam que je lui octroi….
    Chez moi... !!!
    Chez moi, Même s’il n’existe qu’une seule victoire, il n’y a ni compétition et… Ni de tournoi….
    Aux alentours des chiens qui aboient….
    Aux alentours des menaces que je traite bien de…je ne sais quoi ….
    Malgré les difficultés nous vivons bien…sans avoir à être des hors la loi….
    Chez moi… !!!
    C’est t’étrange comme les temps changent….
    Avec tout le bonheur que…mon chez moi dégage….
    Nous sommes à nous seuls un peuple qui emprisonne et…les prisonniers enfermés en cages….
    Un peuple qui déserte et…. Un peuple qui aménage….
    Chez moi… !!!
     Chez moi, Nous vivons trahis comme…. Si nous avons grandi chez Hitler….
    A force d’être suivi par les flics nous… gardons les mains en l’air….
    Mais après tout, la fraternité reste…notre principale filière….
    Africains, nous sommes fort… et ceci pour franchir n’importe quelle barrière….
    Quand l’Afrique parle, c’est…à l’écoute que se met la terre entière ….
    Nous avons assez…
    Assez du gout de cette histoire amère….
    Et du coup Je me dis qu’il est temps… qu’il est temps que l’Afrique se relève et accélère….
    Nous avons l’or…l’uranium, nous n’avons besoin d’aucune aide cuisinière……
    Peut-être que…nous devrions remettre le compteur a zéro et…assurer nos arrières…
    Ou peut-être que…. Nous devrions avancer et…changer nos caractères….
    Il ne faudrait que j’exagère mais….
    Africains on est tous les même…du sang et de chaire….
    Alors relevons nous et…battons-nous pour un Afrique meilleur….
    Et ensemble nous formerons une bel…et grand univers..`, 
    
    `Créature de nature incompris...
    Le silence m'a surpris, et a tout pris des mots qui me restent car chaque j'écris...Et je prie...
    J'ai pris la décision de changer à tout prix...
    J'ai compris qu'il ne s'agit pas de ce que je veux, mais de ce que j'ai appris....
    Au mépris de mon éducation, de l'échec la victoire s'écrit...
    De l'affection, j'ai repris ma quête, réelle est la prophétie...
    Poète si mes mots naissent dans ma poésie...
    Peut-être si je reste fidèle à mes principes, ma tradition féra pareille...
    La confiance se gagne et le respect se mérite, c'est pas pareil...
    Sur les rails qui mènent à la réussite l'échec fait obstacle...
    Chez nous, un plat à deux, se mange souvent à quatre...
    Je suis contre cette pratique...
    Je condamne mon pays...je ne condamne pas l'Afrique...sa direction s'écarte du droit chemin...
    Ma République se classe derrière la négligence, la corruption pleine dans nos mains...
    Les hommes de mains du pays, je fais appel à vous, au plus sages d'entre vous...
    Mon pays est entre vos mains, le destin de mon peuple dépend de vous...
    Défendez-vous...
    Je me défends,  je suis prêt à vous défendre à mes dépends, zéro lâcheté...
    Là je sais, que vous êtes à fond dans vos projets...
    Mais je sais que le cœur de l'Afrique se noie dans ses propres eaux...
    Les petits enfants malnutries dans des hôpitaux, deux ans plutôt...J'entends plus ses battements dans les bâtiments, la jeunesse a peur de se battre, les squelettes ne sont pas que des os...
    mais aussi des supports, deux ans plus tard...
    Chers sont mes mots, ma chaire et ma parole, mes chers le silence est un langage de signe, c'est pour cela que j'apprends à me taire...
    Nos terres sont riches, mais on s'enterre dans la pauvreté...que faire...??
    De l'égoïsme qui nous entraîne...
    Nous divise, nous dirige et nous domine...
    Je n'en sais rien en fait, ils disent qu'il est trop tard, nous sommes dépendants, chaque année on le fête...
    Le fait est que je me plains tellement pour ces gens qui n'ont que peu dans leurs assiettes...
    Qui se réveille chaque matin, pour les travaux champêtres...
    Ils cultivent et récoltent... 
    Vendent ce que l'on achète...
    Ils ne le font pas qu’ il veulent, ni pour des requêtes...
    Ils le font parce qu'ils ont besoin de le faire... envers eux, nous avons une très grosse dette...
    Souvent mon pays à une très grosse tête...
    Mais il oublie ses compatriotes...
    Les hommes de mains du pays, je fais appel à vous, au plus sages d'entre vous...
    Mon pays est entre vos mains, le destin de mon peuple dépend de vous...
    Défendez-vous...
    Ça ne dépend pas de ma religion, ni de la constitution...
    Le droit de l'homme n'a peut-être plus son âme...qui sait ??
    A travers ce slam je vous passe le Salam...
    Au cœur du palabre on se soigne avec des armes...
    Des larmes...on pleure dans les rivières de nos pensées qui se noient dans le besoin...
    Besoins d'amour, quel besoin !!!
    Nous sommes à fond derrière vous...
    Que Dieu bénis mon pays..., Qu'il bénisse l'Afrique et tout le reste du monde...` , `Ma tête noyée dans une marre de dilemme colossal...
    Comment le résoudre ??
    Je me sens sale...mais seul... aux ailleurs de tous ceux qui me condamnent...
    Innocent je me demande pourquoi me nuire les combles...
    Insolents ils se demandent pourquoi le prince convoite la couronne...
    Légitime est-il, mais les gens parlent, pourtant à mes yeux la plupart compte...
    Leurs paroles me blessent... Autant que Ma vérité les racole...
     je fais semblant d'être amnésique car y penser trop me désole...
    J'ai besoin de leur amour...
    Alors dans ma tête je prie...
    
    Oh mon Dieu, donne la chance de voir demain...
    Donne-moi la chance d'être grand...
    Fais de moi un savant...
    Et donne-moi la chance de diriger demain...
    Il faut que je dirige se royaume...
    Il faut je sois fort et grand...
    Il faut que je dépasse leurs attentes...
    Il faut que je continue tout droit...
    Je suis obligé d'avancer...
    
    Tout seul au bord d'une falaise...
    Je porte le poids d'une couronne...
    Persuadé que je peux y tenir...
    Le poids de tout un royaume sur ma tête et mes épaules...
    Je laisse couler ma fierté... et je prie que le bon dieu me pardonne...
    Qu'il pardonne a tous ceux qui veulent me voir tomber...
    La couronne est lourde mais pourtant léger comme...une plume...
    Tout le monde la désir...la plupart deviennent accros et plupart en abuse...
    La plupart finissent vainqueur, mais la plupart finissent au trou...
    risquerait de tomber qui s'amuse à son aise...
    
    
    Je me sens clean mais sale, au milieu de tous ces gens qui me condamnent...
    Ils attendent tous de moi...je dois être meilleur que moi-même...
    Il faut qu'il sache que Mon imperfection me désole...j'ai envie d'être grand, assez grand pour diriger un royaume...
    
    Je rêve toujours, mais ils me racontent que le rêve est autonome...
    Je vie seule mais pas seul, dans la tête de tout le monde je sonne...
    
    Je désire la couronne... Et je l'aurais qu'ils le veuillent ou qu'ils tâtonnent...
    Car le pouvoir me revient, il faut qu'ils me respectent en somme...
    En somme Je me force d'être courtois, car leur amour me console...
    J'ai besoin de l'amour pour vivre, j'ai besoin que vous croyiez en moi...
    
    Si je vous tourne le dos, c'est uniquement parce que subsister dans de l'amour factice me devient fardeau...
    Alors respecter ma façon de vivre, différente de la vôtre...
    Si je suis prince aujourd'hui, demain je serais le roi du slam sans aucun doute...
    PrinceLawan le poète...`, `Un jour voit le jour dans un village maudit...
    Sous l'ombre d'un arbre il avait des sages-femmes réunies
    Le ciel à la fois bleu et clair...
    Les oiseaux dansaient à la salsa à ciel ouvert... 
    La nature devint une vieille femme au visage ridé...le paysage pris de l'âge...
    malgré la stérilité de la terre et l'intensité des rayons solaires...
    Les jeunes se mirent à fond pour faire le nécessaire...
    Ils avaient le devoir de nourrir ce jour de coutume vécue depuis des millénaires...
    De l'autre côté du hangar les hommes se riaient dessus autour d'un dessert...
    Assis sur des trons d'arbre, ils s'appelaient tous d'un nom commun...mon frère...
    Le village était en harmonie et impatiemment en attente...
    Un grand évènement allait se produire... grand-mère nature était particulièrement contente...
    Après un temps fou de fou rire...
    Les festivités commencèrent...
    Ce fut l'arrivée du sultan et de sa Majesté la reine...
    Circonscrit dans un cercle...
    Les marabouts se mirent à lire des versets...
    Les féticheurs firent des sacrifices, le sang fit verser...
    Les femmes dansaient au rythme du tam-tam sans en avoir assez...
    Les poètes déclamèrent chacun sa lignée de versets...
    Et les griots racontaient l'historique de la lignée royale du village...
    Les enfants du bas au moyen âge s'assirent autour et écoutèrent attentivement les éloges...
    Le soleil prie une pause, c'était le beau temps une journée remplie de joie...
    Le village fut en excès de décibels...
    Mais on peut sentir des cœurs battre car ils y croyaient vraiment...
    Le village allait finalement changer de nom...
    Le village allait finalement être béni...
    Pour faire taire le son de la sirène qui envahissait le village...Le sultan, Un homme sage se leva et dit...
    Mes amis, voilà maintenant toute ma vie que je suis au monopole de ce village, et cela vous a coûté toute une loyauté. Et aujourd'hui après des hauts et des bas,  Vous avez su honoré ma personne par votre présence...En tant que chef de ce village, je vous prie d'accepter ce festin en guise de reconnaissance...
    Chacun d'eux, déchaina la pomme de sa main...
    Ils firent des cercles autour de la viande rouge rôti conditionnement...
    Des boissons, du cirop d’érable réservé particulièrement...Pour l'occasion...
    C'était à la fois de la pagaille et de l'affection...
    A les voir profiter au max, on peut se dire que la vie n'est que pour un jour au maximum...
    Pour eux c'était le plus important des jours de l'année...
    Et Soudain le ciel pleura de joie...
    Cela fut des années qu'il n'a pas plu...
    L'eau coula à Flo...
    Les arbres ont immédiatement fleurient...
    Les cours d'eau firent étanché leurs soif...
    Les champs se sont revêtirent des eaux qui les coiffent...
    Et la faune s'abreuva...
    
    Le sultan tendu les deux mains vers le ciel...
    Et remercie le créateur de ses ancêtres...
    Il fit alors un deuxième éloge...et interpella le village sur la question vitale de l'eau et son importance...
    Il ordonna alors au village de faire de son mieux pour être humble afin de commencer une nouvelle page ...
    Voilà donc l'importance impérative de l'eau...,` , `H dans Homme et Humanitéé... 
     H dans Haine et Humilitéé...
     H dans Honneur et Honêtêté...
     H comme la hache de guerre...
     H comme la hache qui creuse et déterre...
     Certains sont comme la lettre H, présent dans Histoire mais n'ont aucune utilitéé...
     
     Il y ‘a un instant, l’histoire fut un temps, dans un système de printemps à la fois libre et compromettant…
     Il y’a plus de cent ans que je suis né, ça fait maintenant plus que longtemps que je bats pour mes idées…
     Écart de six ans entre moi et le lycée, j’ai beaucoup appris de mes trois ans à l’université…
     Le phare et le courant au fond de moi et de ma cité, je suis devenue un combattant qui noirci l’obscurité…
     Un combattant obscur qui tua la paix a coup épée et l’enterra depuis longtemps avant que je ne sois né…
     Les hommes ont fait fi de leurs instincts et mis un terme à leur curiosité, à leur destin il se sont fié…
     Franchement, ils pensaient être des capitaines dévouaéd, mais le temps a révélé qu'il ne sont que des patriotes en panne de loyauté…
     Du berceau de l’humanité, du rêve à réalité, du tort à la sincérité, avant que l’histoire ne devienne conte d’effet, la paix doit être déterrée…
     De la vie à la mort il n’y a pas match en effet, mais il y’a surement une formule de math pour que la paix soit ressuscitée…
     Il n’y a que moi, pour donner vie à cette paix morte depuis l’antiquité...depuis longtemps avant que sois né…
     Avant que je sois ne...
     Les hommes dans leur catégroie se côtoyaient autour d'un feu...
     À ce raconter des faits...
     Pendant que d'autres se broyaient aux coups de feu...
     Dans l'ignorance que la paix est un champs de bataille avec des coupes de champagnes et des faits qui valent le coup d'être dialoguer...
     Mais comment savoir tout cela si la conscience n'est même pas née...? 
     C'est une question que je me suis poser...
     Avant que je ne sois né...
     Avant que je ne sois né... 
     La vie était tellement facile qu'il n'y avait même pas de difficultés...
     Mais la mort est tellement insipide qu'elle te rend visite sans t'avoir contacté...
     Il n'y a pas du mal à vivre seul pour se faire oublier...
     Mais la solitude n'achète pas, elle te fera toujours payé...
     Le prix du sourire et du bonheur, tu seras sans doute privéé de la fraternitéé...
     Et ça je le savais depuis longtemps avant que je ne sois né...
     Mr, dames...avant que je ne sois né...
     Les hommes ne savaient rien de la guerre, ils se font la peine d'être en société...
     Car la survie est un sport d'équipe qui fait réunir toute une communautéé...
     Maintenant que je suis né...
     La vie est tellement bizarre qu'elle te fera pleurer la joie et mourir de rire quand l'autre dans le mal...
     Et ça c'est une réalitéé...
     Depuis longtemps avant que je ne sois né..` , `A court d'amour pas de mots...
     Plus grand est le poète, plus sages sont les mots...
     Sans les mots existe?? t-il un poète...
     Je suis de nature incompris dans ce monde où les innocents font des victimes en grand nombre...
     Heureusement que le silence à tout prix de la colère qui me consume...
     Le cœur a besoin de soin, alors il se couche debout...
     Normal d'en prendre soin quant à la vie l'homme il prend goût...
     Indépendant de nos dépens, Pourquoi briser le cœur d'une femme, au lieu de le défendre...
     Je me défends, j'ai plus d'estime pour l'homme...
     Il est souvent à la hauteur quand on le sous-estime...
     Ils s'estiment et se déclarent vainqueur...
     Dans cette vie temporaire où la victoire est éphémère...
     A quoi bon réussir dans un échec que l'on espère...
     Pourquoi donc les chances de la vie ne s'offrent pas à nos morts...
     Je suis l'héritier de l'homme et de son problème...
     Trop indemne...
     L'homme crains les armes, mais il en crée d'avantage...quel dommage...
     Il aime grand-mère nature mais il tue la faune et abat les arbres...
     Art de vivre...qui est donc professeur à l'école de la vie...
     J'aimerais qu'il enseigne à l'homme le respect de sa propre vie...
     L'homme est de nature laïque, mais la nature à ses lois...
     Il est trop naïf, il perd top souvent la foi...
     Et quand ça tourne au vinaigre, il ne raconte que des salades...
     Pourquoi donc fait-il cela, il aime son être mais il se rend malade...
     Maladroit, il n'y a pas plus que l'homme, trop droit, trop gauche, il n'est jamais fixe...
     Préfixe de ses soucis, il condamne son prochain à un avenir d'Haïti...
     Haïr sans raison, il pollue l'environnement dans lequel il vie...
     Quelle salle demeure, l'homme est Sal, jette des saletés à dieu la santé...
     L'univers se fache, il meurt très vite...
     L'atmosphère a déjà deux trous dans le cœur à cause de ses bêtises...
     Qu'il refuse de corriger...
     L'univers est en danger...
     Mais l'homme s'en tape, s'en moque, s'en contre fou, comme s'il serait sauve quand il n'aura plus de chez lui...
     L'homme...
     PrinceLawan...
     ` , `Les deux mains vers le ciel...
     J'implore mon créateur, qu'il bénisse, nous pardonne et nous octroi la chance de voir demain...
     Demain...
     Demain c'est dans quelques heures...
     Seul dans la nature, je pense à l'avenir...
     Ceux qui se lèvent tôt finissent par aboutir...
     Alors je me réveille très tôt le matin pour m'abonnir...
     Je crois au destin, mais chacun est maître du sien...
     Je ne crois pas aux crétins qui me racontent des baratins...
     Je n'ai pas confiance à demain je profite du moment présent...
     Je serais peut-être mort demain, alors je réponds au mal par le bien...
     Je n'ai pas confiance au soutien qui me hantera demain...
     Je préfère bâtir tous seul mon demain...
     Demain c'est loin, mais demain c'est aussi dans quelques heures...
     Demain...
     L'aube sera belle à l'horizon,  mais le crépuscule sera magnifique dans douze heures...
     La nuit sera sombre demain, mais les étoiles seront belles quand même...
     Ne perd pas espoir, t'inquiète, Demain effacent les problèmes...
     Car demain peut-être aussi belle qu'un poème...
     Demain...
     Demain est capable de te rendre riche, demain est capable de te briser ton petit cœur...
     Demain est sans pitié, c'est pour que demain me fait demain me fait peur...
     Demain j'oublierais mon chagrin, car demain est une éponge...
     Demain n'est pas très loin c'est juste dans quelques heures...
     Demain...
     Demain ton premier amour...
     Demain ton dernier tour...
     Demain ton premier cour...
     Demain ton dernier jour...
     Demain c'est la pleine lune...
     Le ciel sera magique sur les dunes...
     Demain le beau temps...
     L'agriculteur sera content...
     Les esprits seront calmes demain,  le paysage sera cool...
     Demain...
     Demain il y'aura l'histoire mais plus d'historiens...
     Demain Il y'aura de l'espoir, mais plus de soutien...
     Demain il y'aura de pouvoir, mais plus de dirigeants...
     Demain il y'aura des miracles mais peu croiront...
     Demain il y'aura beaucoup de religions, mais peu de croyant...
     Demain...
     Demain, la vie n'est pas une évidence...
     Je suis peut-être de vôtres a présent, mais demain je n'aurais plus d'existence...c'est évident...
     Demain est sans pitié...demain me fait peur, mais d’heures c'est juste dans quelque heure...
     Demain n'est pas une certitude...
     On a cette habitude...
     De se dire à demain sans aucun doute...
     Sans aucune inquiétude...
     On aime tellement demain...
     Qu'on repose l'avenir sur ses épaules...
     Mais demain est un mystère loin d'une devinette à l'école...
     Demain me fait peur, c'est juste dans quelque heure...
     Demain...
     Demain la pêche sera bonne...
     La chasse sera bonne...
      Mais il faut de la chance pour voir demain...
     Car on peut mourir maintenant...
     Même s'il reste quelque heure...
     Demain...
     Demain ton premier amour...
     Demain ton dernier tour...
     Demain ta première cour...
     Demain peut-être ton dernier jour...
     Ne fais jamais confiance à demain...
     Profite du moment présent...
     Et répond au mal par le bien...
     Car demain n'est pas une évidence, mais un mystère c'est évident...
     `, `Il y'a bien des corrections qui peuvent être synonymes d'affection. ils se demandent tous comment ce petit prince arrive à aider ses proches avec compassion, c'est peut-être parce que je ne laisse pas ma passion prendre le dessus sur mes bonnes intentions, une chose est sûre, toute action engendre une réaction, donc ça ne sert à rien d'agir en toute façon.
     On ne le souhaite pas du tout mais dans la vie, chacun de nous vit des moments difficiles, des moments qui conduisent certains d'entre nous au suicide, parfois des épreuves pires que la mort, alors toi qui lis mes écrits, je tiens à te dire que, la souffrance, le KO, la douleur, le désespoir, la colère, l'amour, la confiance, la trahison, sont des choses qui définissent notre nature, alors pourquoi donc ne pas laisser la nature faire son travail ?, parce que personne ne façonne notre destin à notre place.  Personnellement, j'ai aussi vécu des moments de bonheur et bien sûr de déespoir, des moments qui m'ont enlevéé goût à la vie, des moments qui m'ont détachéé de mon entourage. Au lieu d'encaisser et patienter à ces épreuves, j'ai passéé ma vie en penséée et je n'ai pas vraiment aimé l'expérience. Crois moi, à part la jalousie, trop penser fait aussi maigrir.
    Toi qui lis mes éécrits, prends soin de toi. En fait c'est juste une manière pour moi de te rappeler que la vie c'est donnant donnant, fais toi respecter,  ne demandes pas trop de service à l'homme parce que l'homme à un sale caractère,  il n'est pas aussi confiant qu'il en a l'air, c'est comme on dit l'apparence est souvent trompeuse. Plus tu lui demandes, plus il te sous-estime et de déteste. Au final tu seras en tête d'affiche, dès que tu prends un virage, il dira le voilàà qui arrive. Pourquoi tout ce cirque si il y a ton créateur qui est toujours là pour toi,  et qui aura le plaisir de t'offrir ce que tu désir, rien qu'en ouvrant ton clapet pour demander ?? 
    C'est naturel qu'après la pluie vient le beau temps, après la difficultéé vient  la facilitéé, ça aussi c'est naturel. Abandonner facilement face aux épreuves, c'est naturel chez l'homme. Il y'a parmi nous ceux qui voient les choses autrement. Toi qui lis mes éécrits, tu n'es peut-être pas celui que tu crois être, je sais qu'au fond de toi il y a bien ce cœur qui désire que tu laisses tout tomber à cause d'une chose passagère qui te méprise, rends moi service,  réfléchis,  parce que, réfléchir c'est naturel et indispensable chez l'homme. Ce petit cœur en toi peut un jour devenir grand, aussi grand qu'il y aura de la place pour tes ennemis. Il faudrait juste faire couler une île de bonnes intentions dans tes veines. Je sais que tu es entrain de te dire que c'est du sang qui devait couler dans tes veines pas des intentions, alors saches une chose, ce sont nos intentions qui caractérisent le sang que nos cœurs pompent. Tu as peut-être essayer,  mais saches que essayer c'est échouer, alors mettre en application c'est la meilleure des solutions. 
    Il nous arrive parfois de faire des mauvais choix pour la bonne raison, des décisions difficiles, parce que le courage c'est prendre de risque. Il nous arrive parfois d'aimer une personne sans le savoir , mais jamais il ne nous arrivera d'échapper à nos mauvaises habitudes tant que nos cœurs décident à notre place. C'est comme on dit : Quand les armes parlent, tout le monde se tait. Il nous arrive même parfois de sentir qu'on déteste une personne même si celle-ci n'a rien fait de mal. C'est vrai, dans la vie on a besoin d'être entouré, mais il nous arrive parfois d'avoir un besoin d'être seul. 
    Comme on dit la vengeance est un plat qui se mange froid, alors je me demande pourquoi certains d'entre nous ne peuvent pas patienter et préfèrent le manger chaud ?.  Si une personne fait une action contre toi, elle s'attend à ce que tu  réagisses pour qu'elle puisse déterminer tes faiblesses. Pourquoi dans ce cas lui donner ce luxe ?  Oublies la et fais comme si de rien n'était, tu verras qu'elle viendra d'elle même pour s'excuser. Parfois c'est en voulant se faire remarquer qu'on commet une grave erreur qui pourrait nous déplumer l'honneur.
    Bien sûr, Qu'on peut blesser rien qu'avec les mots. Le savoir est une arme, qu’ avec le savoir on peut détruire, avec le savoir on peut construire. Personnellement, sans flatterie j'utilise mon savoir pour aider mon monde,  mais d'autres l'utilisent pour régeler leur compte. Je leur dirai de savoir utiliser leur savoir avant que l'heure sonne. 
    `, `Bonsoir à tous monde...J'ai une question qui me demange...
    Dites-moi svp, ça fait quoi ?  Ça fait quoi de voir beaucoup de choses dans sa vie
    Parce que Dans ma vie  à moi j'ai vu plein de trucs je vous assure...
    Pas trop de bauls je vous rassure !
    J'ai vu des hommes, des hommes partir...
    J'ai eu peur...et j'ai perdue goût à la vie...
    J'ai vu ma grand mère piler le mil ,le poignet ferme comme si ça tenait à sa vie..
    Ça a été beau à voir...
    Les souvenirs parviennent toujours à m'émouvoir...
    Et J'ai vu la médecine sauver des vies...
    Ça m'a redonné de l' espoir...
    Les sentiments de vie... que l'on exprime...
     La joie de la vie l’horizon qui se dessine...
    La vie et ses énigmes...
    Le corps et son régime...
    Tout tourne autour de la santé et de la durée que la vie nous estime...
    J'estime que le temps fait des victimes...
    Et que Les médecin empêchent des crimes... 
    Mais Je refuse de voir nos hôpitaux remplis de façon urgentissime...
    Je refuse de voir nos mères mourir pendant l'accouchement...
    Je refuse de voir nos frères vivre des cauchemars...
    Je refuse de voir nos médecins se réveiller au chômage...
    Il a L'expertise et le courage, le médecin  profite à la Nation depuis le moyen âge...
    Depuis que les labos n'existent pas sur le rivage...
    Depuis que grand mère sur ses pats elle voyage...
    Depuis que le livre de l'histoire est à la première page...
    
    Sur la première page de mes écrits je me suis senti obligé de l'écrire car je sais qu'il faut du courage, du charisme,  et de la détermination pour  faire face à certaines situations...
    Un patient en apnée, l'autre enrhumé, l'autre perd la raison, L'autre dans le coma, tous sur un lit d'hôpital, attente d'une solution...
    Alors que Tous savent pertinemment qu'un médecin n'est pas un oracle meme s'il fait des miracles parfois...
    Parfois L'espoir de vivre nous fait oublier que la santé est primordiale...est ce qu'il faut être souffrant pour en connaître l'importance...? 
    L'important est que Pour sauver des vies le médecin fait de son mieux...
    Mais l'avenir demande plus, deux fois plus de courage pour deux fois plus d'expertise, avec deux fois plus de détermination pour deux fois plus de monde en quête d'assurance...
    Car La vie et ses éénigmes, Le corps et son régime tout  tournent autour de la santé et de la durée que nous estime le seigneur des cieux...
    les médecins je vous respecte, recevez la bénédiction de ma grand-mère depuis ma terre ancestrale...
    `, `J'ai essayé d'être juste...
    Mais l'injustice m'a épousé...
    J'arrive plus à me divorcer...
    Le temps m'a puni, j'arrive plus à me soutenir...
    Les frères m'ont soutenu ça me fait plaisir de me souvenir...
    Il faudrait que je change j'ai assez perdu de temps...
    Il est temps que j'apprenne, dans le pire et dans le confort...
    Il est temps que je leur disent et que j'assume mes tords...
    J'ai encore des qualitésés malgréé l'influence de mes défauts...
    Quand Le passé m'a brisé le dos, mama était là pour m'en faire cadeaux...
    Je transporte mes fardeaux...
    Car Dans le royaume de mon succès je reste le bourreau...
    Mon passé à rendu l'âme, mais il revient me hanter...
    Je dois être comme une lame pour pouvoir le trancher...
    Le passé m'agresse, si je suis Costaud comme une défaite, c'est parce que  la solitude m'engraisse...
    Je ne suis pas un héro...certains critiquent ma race, d'autres condamnent mon ego... 
    Mon passé est tranchant, il m'a déjà pris mon âme sœur...
    On ne peut pas être invincible avec des blessures dans le dos...
    L'amour m'a tiré dessus...d'une flèche dans le cœur...mais je ne suis pas Roméo...
    j'écris ma tristesse sur l'eau...et comme la science est exacte elle coulera à flot...
    Pour ne pas verser des larmes Je garde les yeux en l'air...Même une rupture amoureuse est plus belle que ma rancœur...
    Mes penséées sont prises en otage mais sans rancune , Ça fait des années que  Je m'inspire de la douleur...
    Mon avenir en apnée, je dois respirer de l'espoir avant que mes projets ne s'étouffent...
    Le chemin vers l'amour est no limit...
    Mais bizarrement ma pineco m'a largué au bord de la route...
    J'ai les yeux qui transpirent...
    Dans l'ombre de ma haine se cachent des vampires...
    Rien n'est moins sûr car je suis seul dans ma défaite...
    Les proches ne me soutiennent plus...
    Mon réveil ne sonne plus...
    Verser des larmes ne me suffit plus...
    Quand tu réussi dans ta vie ont dit que même ta chance t'obei...
    Mais quand t'as les poches vide même tes parents ne te veulent plus...
    Ta société te vomie, te traite d'antipathique...
    Ils attendent à nouveau que tu échoue...pour dire, je te l'avais dit...
    Beaucoup accordent le pardon, mais la plupart ont les poitrines remplis de vides...
    Est-ce vraiment ça l'humanitéé...
    Un agencement d'animaux aux funérailles de la vérité...
    La sincérité n'existe plus...
    Depuis l'enterrement de ma vie de gosse je ne fais que grandir certains m'appelle le boss...
    J'ai bossé sur le chantier de ma vie, hors de question que je laisse ma fiertéé détruire mon éédifice...
    J'ai pas besoin de leur célébrité pour briller dans la peau d'un artiste...
    Je suis un artiste, un slameur je n'y peux rien, mon destin est tracé, au développement de ma race il faut que j'assiste...
    J'ai eu l'habitude de pleurer quand les racistes me traite de sale noir...
    Dite leurs que maintenant je ne suis plus ce sale gosse...je suis PrinceLawan, le slameur du désert...
    Je ne suis plus comme avant...
    Demande juste au soleil, il te dira que le désert est l'endroit où habite la chaleur...
    Il te dira aussi que je suis le slameur du désert..
    `, `Nous vivons dans un monde où chacun cherche à juger l'autre...
    Nous sommes tellement aveuglé par l'envie de connaître l'autre qu'on se blesse parfois en blessant d'autres...
    Nous sommes tellement malhonnête au point de comploter derrière le dos de l'autre jusqu'à manger la chaire de la peau de l'autre...
    Et pour être honnête...
    Ne juge mon apparence...
    Juge moi selon mes actes...
    L'apparence est souvent trompeuse...
    La parole de mes ancêtres...
    J'n'ai pas le choix moi, de définir mon existence...
    Depuis le début des temps mon destin à été tracé,  scellé...
    C'est comme la présence d'une aiguille dans le salon d'une coiffeuse...
    Rien d'étonnant, ce n'est pas de ma faute si je doit vivre dans ce monde des pervers...
    Pas étonnant que je mange sur leur terre...après tout j'suis qu'un humain et au dernière nouvelle l'être humain est imparfait et gavé d'ignorance...
    Tu ne peux pas le juger , Il a esprit pervers et tatoué d'arrogance...
    Pour être franc....,
    Ne juge pas mon éégoïsme, le partage est un luxe que je ne peux pas me fixer surtout que je vis dans un monde éégoïste...
    Je ne vois Rien d'égoïste à vouloir se méfier de l'autre, c'est chacun pour soi dans ce monde des racistes...
    Ne juge mon impatience, Je suis impatient je l'avoue mais pas plus qu'un patient sur un lit d'hôpital...
    L'homme prétend forgé son destin,  en fait c'est le destin qui forge son homme..ça c'est sûr...
    Je nomme PrinceLawan, pas parce que je suis de sang royale, mais parce que j'ai  a pas besoin d'être de sang royal pour diriger un royaume...
    Ce royaume de slam que je apprendre à connaître, parce qu' il est à présent ma seconde nature...
    Ils jugent la nature..
    Il se plaint qu'avec eux la nature à été injuste, mais ils continuent de se nourrir d'orgueil,  pourtant ce sont eux les injustes...
    Pour être juste...
    Ne juge pas ma nature...
    Comme toi je ne suis qu'une créature du créateur...
    Parfois les décisions à prendre dépassent ma ceinture, Mais sache que je ne suis pas immature...je continuerai d'avancer dans le calme au volant de ma voiture...
    À force de me juger, juges toi toi même, Si seulement tu sais ce qui t'attend une fois six pieds sous terre, tu ne te feras jamais la peine d'être en aventure comme tu l'es à présent...
    Tu pleureras toute les larmes de ton corps,  et tu finiras ta vie noyaé dans le regret de tes tords...que c'est tragique...
    toute ta vie est limité c'est comme un film d'horreur dont l'acteur à la destinée innéeée...
    Pour ne pas te condamner...
    Ne juge pas mon futur...On à pas le même sourire, sans doute pas le même sens de l'humour...
    Ne me juge pas selon mon sourire, il est peut être le masque du désespoir qui se cache au plus profond de mon cœur...
    Pourtant J'ai le cœur net, Car je ne suis pas le genre à me laisser éduquer par Internet... 
    Pour être honête...
    Ne juge pas mon éducation...
    `, `D'habitude la vie dans tous ses sens est à la fois dure, mais douce et simple comme on le dit...
    Comment dire que celle d'un étudiant est à la fois remplie de beaux rêves, des faux espoirs et des projets innovants enterré sous  un lit...
    C'est vrai dans la vie les rêves et la réalité ne s'accordent pas toujours...
    Mais nos rêves peuvent être réalisés quand on décide de les vivre au jour le jour...
    Je n'ai jamais cessé de me battre depuis le jour où l'on m'a dit que le savoir est une arme...
    En tant qu'étudiant Je me demande Comment raisonner  si l'on a la conscience attachée à un arbre...
    comment changer le monde si l'on a les cœurs derrière des barreaux...
    Comment changer les autres si on manque de cerveau...
    Dans mon cerveau d'aussi loin que je me souvienne,  Haoussawa sou na thé min " illimi lantarkin dounia" "Mai nemah ya na tare da samou"
    Parfois il est difficile de trouver ce que l'on cherche, tout le monde le sais...
    Mais avec la difficulté il y'a toujours la facilité, personne ne peut le nier...
    personnellement, Some times I had stupid need to give up,  to disgorge what I learned...
    But I resist,...I refused to devot...I continue to progress...Jusqu'à ce que les choses se calment...
    
    Mature je le suis...envers mes enseignants je suis poli, le rôle que joue ma politesse est synonyme de ma force de jeunesse...Cette force m'a donné le courage et le plaisir de me tracer un chemin...pour qu'à la quête du savoir j'accelère sans actionner mes freins...
    
    Sur ce chemin il m'est arrivé de vouloir changer d'air, de découvrir un autre milieu, d'étudier même sur la lune si la nature me le permet...
    
    Students, teachers, doctors, professors, Africa needs us...we have to stand up...we have to go ahead and get success...for our Africa...
    
    Cette union qui nous unie en une seule âme et fait de nous un seul corps que j'appelle Afrique...
    
    Slam... 
    `, `Je pleure dans le silence...et Si tu vois mes larmes couler...ne viens pas me dire de les essuyer...ça fait des années des que je les stock...je crois que j'en ai assez...
    J'ai assez perdu des proches, j'ai assez souffert dans la vie...Il faut que cette douleur déménage...Pour faire place au bonheur dans ma vie...
    Laisse-moi pleurer mes morts, Laisse-moi faire mon deuil... et je te promets que la lutte continue jusqu'au seuil de leur défaite...
    Jusqu'à ce que la victoire soit au seuil de nos portes...
    Jusqu'à ce que indépendance soit à nouveau dans nos poches...
    je ne veux pas que ma vie soit un fardeau pour les autres...
    Non...Je veux qu'ils sachent que je suis avec eux dans le meilleur et dans le moche...
    Nous sommes le signe du courage il y'a de l'espoir est dans nos regards...
    Restons Nigériens, synonyme de force pas de peur...
    Rester à genoux c'est pas mon genre même s'il parvient à m'emputer les jambes...
    Je reste Debout...
    La force circule dans mes veines, car je suis un soldat africain, une force Nigerienne...
    Hommage à Nos FDS, combattant et défenseur de la frontière...
    Beaucoup ont perdu leur vie au service de la mienne...
    Beaucoup on fait face à l'ennemi pour garder leur dignité Nigerienne...
    Je me sens nul, méprisè et sans aucun pouvoir...comment pourrai je aider les aider avec un job d'étudiant ?
    
    Un message À tout ces sales racistes qui nous traitent de sale Negro...
    Qui prétendent nous aider en nous poignardant dans le dos...
    Qui se prive de sommeil pour que l'Afrique demeure dans le coma...il n'y a pas pire que vous...
    Je ne veux pas de leur compassion... je ne serais moi même qu'en les voyant partir...
    Ils ont tué ma jeunesse pour m'empêcher de grandir...
    Ils ont charmer ma conscience, maintenant je me bat contre moi même...ils disent que le noir que le noir Nigérien est né pour servir...
    Les hypocrites, sachez que le noir est né pour réussir...
    Il est Armé jusqu'au dents et le courage plein les poches...
    Hommage à nos FDS...
    
    J'ai la haine pleine les poches, on dirait un africain grandi chez Hitler...
    Je préfère immortaliser mon existence en tant qu'enfant soldat que de mendier à leur porte ce qui me revient de droit...
    Chers Nigériens je suis à court de paroles...je préfère me taire que de faire pleurer ma daronne...
    Je m'appelle prince Lawan, le slameur du désert, le slameur révolutionnaire, Je viens d'arlit...Nigerien et fier de l'être...
    Ensemble jusqu'au bout dans le meilleur ou dans le pire...
    `, `Un jour
    Un jour tout sera fini...
    La vie ne tiendra même plus qu'à un fil... 
    Ce monde atteindra sa limite... 
    Le vent soufflera à grande vitesse et le temps passera moins vite...
    Un jour le soleil frappera fort du ciel sous lequel on s'abrite...
    Le soleil se lèvera à l'ouest, c'est le jour de la panique...
    Un jour le plus bavard deviendra timide...
    Tout le monde sera soumis, les pauvres, les riches et même les élites...
    La terre se repliera sur elle-même, emportant tout ce qui y habite...
    Un jour nos frères nous fuiront, nous serons seul à affronter ce que le prochain nous destine...
    Un jour on se réveillera, les larmes aux yeux, regardant la famille se noyer dans la défaite...
    L'histoire s'arrêtera et personne ne racontera plus rien, rien ne nous sera dédié... 
    Plus rien ne restera même les vestiges des plus courageux... 
    Un jour la panique prendra le dessus, le sens de l'humour se gèlera par la suite... 
    La suite sera douloureuse pour certains, mais apaisante pour d'autres vies... 
    Rien que d'y penser...
    Un jour la vie privée de tout le monde sera dévoilée, plus de journal intime... 
    Plus de cachette secrète,  plus de secret caché... 
    Trop tard pour les regrets, nos actions ont déjà mis le cachet...
    C'est la fin, Le cris du silence nous envahira, c'est loin d'être la douceur... ...
    Un jour, l'humain rêvera de battre le record du bonheur...
    Mais hélas, on ne joue plus aux jeux vidéo, la réalité est dans son heure... 
    Les gens verseront des larmes certes...
    Mais aucune facture, car ce jour-là, la rivière sera à sec... 
    Un jour Plus de retard de loyer, on rendra tous des comptes et la vérité jaillira de nos sacs... 
    Le temps sera perdu, à jamais les aiguilles ne feront plus des tic-tac... 
    L'amour n'existera plus, c'est chacun pour soi Dieu pour tous, comme l'histoire de l'Afrique...
    Un jour on serait tout seul perdu dans des aventures tragiques...
    Un jour on quittera ce bas monde, c'est d'ailleurs la réalité qui n'engage aucune politique... 
    Par ailleurs, commence la quête du secours, Parce que depuis ce jour-là vie n'aurait le même goût... 
    Il n'y aurait plus de caisses pour encaisser, mais on payera qu'en même car chaque chose a un coût...
    Pourvu qu'un jour nous serons parmi ceux qui ont été patient et écouter les beaux discours... 
    Un jour tu partirais loin d'ici, loin de ta famille et loin de toi même... 
    Tu seras ravi d'apprendre que le paradis est ta demeure pour l'éternel... 
    C'est comme ça, Une page finie une autre s'ouvre, le livre demeure infini...
    `]


    poete.addEventListener('click', function magana () {
        var numpoesie = Math.floor(Math.random()*(14));
        document.getElementById('slam').innerHTML = poesie[numpoesie];
    })